#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.xamarin.example.tabhostwalkthrough.Resource", IsApplication=true)]

namespace com.xamarin.example.tabhostwalkthrough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_my_schedule = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_my_schedule_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_my_schedule_unselected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_sessions = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_sessions_selected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sessions_unselected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_settings_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_settings_unselected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_speakers = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_speakers_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_speakers_unselected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_whats_on = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_tab_whats_on_selected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_tab_whats_on_unselected = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int scrollView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int textView3 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textView4 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textView5 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView6 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int textView7 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView8 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textView9 = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int webViewDiscover = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int webViewMyChannel = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int webViewSettings = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int webViewSubs = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int webViewWhatsOn = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int discover = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int myChannel = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int subs = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int whatsOn = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
